name: Update readme joke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  update_readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: cargo run --verbose
    - name: Update joke on readme file.
      run: |
        git config user.name "Automated Publisher"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -f README.md
        git commit -m Update joke!
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
